---
title: "DOW Jones Index Case"
author: "Visha Arumugam(vcu526), Michael Grogan(ldl776),Sanyogita Apte(jlh562)"
date: "October 31, 2021"
output: html_document
---
<style type="text/css">

h1.title {
  font-size: 38px;
  text-align: center;
}
h4.author { 
  font-size: 18px;
  text-align: center;
}
h4.date { 
  font-size: 18px;
  text-align: center;
}
</style>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Task: Build models to predict stock prices and evaluate risks of stocks. 
#Target per percent_change_next_weeks_price
#Models to try: Linear Regression, Decision Trees, SVM

#All use-able variables:
#percent_change_price+percent_change_volume_over_last_wk+time+open+days_to_next_dividend+percent_return_next_dividend+close+high+low+stock+previous_weeks_volume+volume

#Variables used in original study:
#percent_change_price+percent_change_volume_over_last_wk+days_to_next_dividend+percent_return_next_dividend


library(Boruta)
library(caret)
library(imputeTS)
library(e1071)
library(rpart)
library(tseries)
library(quantmod)
library(reshape2)
library(lubridate)
library(ggplot2)
library(tidyverse)

setwd("~/GitHub/DA6813CaseStudies/Case3")
#setwd("~/MSDA/Fall 2021/GitHub")
#setwd("~/MSDA/Fall 2021/GitHub/DA6813CaseStudies")
#setwd("~/MSDA/Fall 2021/Data Analytics Applications/Case Study 1/DA6813CaseStudies/Case2")
#setwd("~/MSDA/Fall 2021/Data Analytics Applications/Case Study 1/DA6813CaseStudies/Case3")
```






```{r}
DOWdata<-read.table('dow_jones_index.data',sep=",",header=T)


for(i in c(4:7,12:13)){
  DOWdata[[i]]<-as.numeric(gsub('\\$','',DOWdata[[i]]))
  
}
DOWdata$date<-as.Date(DOWdata$date,format ="%m/%d/%Y")
DOWdata=na.ma(DOWdata)
DOWdata$time<-as.numeric(DOWdata$date)
q1<-unique(DOWdata$date[DOWdata$quarter==1])
q2<-unique(DOWdata$date[DOWdata$quarter==2])


for(j in list(q1,q2)){
  for(i in 1:length(j)){
    DOWdata$time[DOWdata$date==j[i]]<-i
}
}

# vars= names(DOWdata)[4:length(names(DOWdata))]
# for(v in vars){
#   var_name=paste(v,"lag",sep="_")
#   print(var_name)
#   print(typeof(var))
#   DOWdata$as.character(substitute(var_name))<-lag(DOWdata$as.character(substitute(var)),n=1)
   #DOWdata=DOWdata %>%
  #         group_by(stock) %>%
  #         mutate(var_name :=dplyr::lag(v,n=1)) %>%
  #         ungroup()
 #}


# Open Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(open_lag=dplyr::lag(open,n=1))

# High Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(high_lag=dplyr::lag(high,n=1))

# Low Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(low_lag=dplyr::lag(low,n=1))

# Close Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(close_lag=dplyr::lag(close,n=1))

# percent_change_price
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(percent_change_price_lag=dplyr::lag(percent_change_price,n=1))

# Percent Change Volume Over Last Week Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(percent_change_volume_over_last_wk_lag=dplyr::lag(percent_change_volume_over_last_wk,n=1))

# Percent Change Next Weeks Price Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(percent_change_next_weeks_price_lag=dplyr::lag(percent_change_next_weeks_price,n=1))

# days_to_next_dividend_lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(days_to_next_dividend_lag=dplyr::lag(days_to_next_dividend,n=1))

# Percent Return Next Dividend Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(percent_return_next_dividend_lag=dplyr::lag(percent_return_next_dividend,n=1))

# Next Weeks Close Lag
DOWdata=DOWdata %>%
group_by(stock)%>%
mutate(next_weeks_close_lag=dplyr::lag(next_weeks_close,n=1))

# Next Weeks Open Lag
DOWdata= DOWdata %>%
group_by(stock) %>%
mutate(next_weeks_open_lag = dplyr::lag(next_weeks_open, n =1))

# Volume Lag
DOWdata= DOWdata %>%
group_by(stock) %>%
mutate(volume_lag = dplyr::lag(volume, n =1))

# Previous Volume Lag
DOWdata= DOWdata %>%
group_by(stock) %>%
mutate(previous_weeks_volume_lag = dplyr::lag(previous_weeks_volume, n =1))

train<-DOWdata[DOWdata$quarter==1,]
test<-DOWdata[DOWdata$quarter==2,]

train<-na_ma(train)
test<-na_ma(test)

#str(train)
```
```{r}
head(train)
```



```{r}
#index for CAPM
DOWIndex <- read.csv("DOW_2011Q1Q2.csv", header=TRUE, sep=",") 
closedf<-as.data.frame.matrix(xtabs(~date+stock,DOWdata))
for(i in unique(DOWdata$stock)){
closedf[i]<-DOWdata$close[DOWdata$stock==i]
}

closedf$DOW<-DOWIndex[,5]

Returns<-na.omit(apply(closedf,2,Delt))
boxplot(Returns,main="Expected Return", xlab="Stock Picks", ylab="Return",las=2)

CAPM<-data.frame(matrix(ncol = 2, nrow = 0))

for(i in unique(DOWdata$stock)){
betta<-summary(lm(as.formula(paste(i,"DOW",sep="~")),as.data.frame(Returns)))
CAPM<-rbind(CAPM,c(i,betta$coefficients[2,1]))
}
colnames(CAPM) <- c("Stock","Beta")
CAPM
```




```{r}
#writing formulas

#static formulas
targety<-"percent_change_next_weeks_price"
fvar<-c("percent_change_price","percent_change_volume_over_last_wk","time",
        "open","days_to_next_dividend","percent_return_next_dividend","close",
        "high","low","stock","previous_weeks_volume","volume")
fvarsvm<-c("percent_change_price","percent_change_volume_over_last_wk","time",
        "open","days_to_next_dividend","percent_return_next_dividend","close",
        "high","low","previous_weeks_volume","volume")
ovar<-c("percent_change_price","percent_change_volume_over_last_wk",
        "days_to_next_dividend","percent_return_next_dividend")

flagvar=c("percent_change_price_lag","percent_change_volume_over_last_wk_lag",
        "open_lag","days_to_next_dividend_lag","percent_return_next_dividend_lag","close_lag",
        "high_lag","low_lag","stock","previous_weeks_volume_lag","volume_lag")
flagvarsvm<-c("percent_change_price_lag","percent_change_volume_over_last_wk_lag",
        "open_lag","days_to_next_dividend_lag","percent_return_next_dividend_lag","close_lag",
        "high_lag","low_lag","previous_weeks_volume_lag","volume_lag")
slagvar<-c("percent_return_next_dividend_lag","low_lag","open_lag","close_lag","high_lag","volume_lag",
        "previous_weeks_volume_lag","stock")


#full=c(fvar,flagvar)
#optimized formulas, svm needs to have stock excluded because it can't calculate without variation
svar<-c("time","time:percent_return_next_dividend","close","stock")
svarsvm<-c("time","time:percent_return_next_dividend","close")


selectformula<-as.formula(paste(targety,paste(svar,collapse="+"),sep="~"))
fullformula<-as.formula(paste(targety,paste(fvar,collapse="+"),sep="~"))
originalformula<-as.formula(paste(targety,paste(ovar,collapse="+"),sep="~"))

selectformulasvm<-as.formula(paste(targety,paste(svarsvm,collapse="+"),sep="~"))
fullformulasvm<-as.formula(paste(targety,paste(fvarsvm,collapse="+"),sep="~"))


fulllagformula<-as.formula(paste(targety,paste(flagvar,collapse="+"),sep="~"))
slagformula<-as.formula(paste(targety,paste(slagvar,collapse="+"),sep="~"))

fulllagformulasvm<-as.formula(paste(targety,paste(flagvarsvm,collapse="+"),sep="~"))
```


```{r, echo=F, eval=F}
#boruta_var_imp_output=Boruta(fulllagformula,data=na.omit(train),doTrace=1)
#boruta_signif <- getSelectedAttributes(boruta_var_imp_output, withTentative = TRUE)
#boruta_roug_fix_mod=TentativeRoughFix(boruta_var_imp_output)
#Variable Importance Scores
#boruta_imps <- attStats(boruta_roug_fix_mod)
#boruta_imps2 = boruta_imps[boruta_imps$decision != 'Rejected', c('meanImp', 'decision')]
#boruta_imps2[order(-boruta_imps2$meanImp), ]
#plot(boruta_var_imp_output, cex.axis=.7, las=2, xlab="", main="Variable Importance")
```


```{r}
## Train models
selectlm<-glm(formula=selectformula,family="gaussian",data=train)
fulllm<-glm(formula=fullformula,family="gaussian",data=train)
originallm<-glm(formula=originalformula,family="gaussian",data=train)

selectsvm<-svm(formula=selectformulasvm,data=train)
fullsvm<-svm(formula=fullformulasvm,data=train)
originalsvm<-svm(formula=originalformula,data=train)


#selecttree<-rpart(formula=selectformulasvm,method = "anova",data=train) can't handle interaction
fulltree<-rpart(formula=fullformulasvm,method = "anova",data=train)
originaltree<-rpart(formula=originalformula,method = "anova",data=train)

fulllaglm<-glm(formula=fulllagformula,family="gaussian",data=train)
siglaglm<-glm(formula=slagformula,family="gaussian",data=train)

fulllagsvm<-svm(formula=fulllagformulasvm,data=train)

fulllagtree<-rpart(formula=fulllagformulasvm,method = "anova",data=train)
```

```{r}
#Results_df<-data.frame(matrix(ncol = length(unique(test$stock)), nrow = 0))
#colnames(Results_df)=unique(test$stock)
```




```{r}
#Change model to compare
#Compares prediction on data that was used to train the model and then on new test data
#Due to some stocks having more outliers than average, the training data can yield even worse predictions


modellabels<-c("selectlm","fulllm","originallm","selectsvm","fullsvm","originalsvm","fulltree",
               "originaltree","fulllaglm","siglaglm","fulllagsvm","fulllagtree")
modellist<-list(selectlm,fulllm,originallm,selectsvm,fullsvm,originalsvm,fulltree,
                originaltree,fulllaglm,siglaglm,fulllagsvm,fulllagtree)


results<-as.data.frame(matrix(ncol=5,nrow=0))
colnames(results) <- c("Model","Stock","TrainMSE","TestMSE","Beta")

for(m in 1:length(modellist)){
for(i in unique(test$stock)){
model<-modellist[[m]]
target<-test[test$stock==i,]
prediction<-predict(model,target)


trainstock<-train[train$stock==i,]
trainedpred<-predict(model,trainstock)


trainmse<-mean((trainedpred-trainstock$percent_change_next_weeks_price)^2)
testmse<-mean((prediction-target$percent_change_next_weeks_price)^2)


resultrow<-c(modellabels[m],i,trainmse,testmse,CAPM$Beta[CAPM$Stock==i])
results<-rbind(results,resultrow)

#par(mfrow = c(1, 2))
#plot(trainstock$time,trainstock$percent_change_next_weeks_price,main=paste("Train:",i,"MSE:",round(trainmse,3)))
#lines(trainstock$percent_change_next_weeks_price,col="red")
#lines(trainedpred,col="blue")

#plot(target$time,target$percent_change_next_weeks_price,main=paste("Test:",i,"MSE:",round(testmse,3)))
#lines(target$percent_change_next_weeks_price,col="red")
#lines(prediction,col="blue")

}
}
colnames(results) <- c("Model","Stock","TrainMSE","TestMSE","Beta")
results$Difference<-(as.numeric(results$TestMSE)-as.numeric(results$TrainMSE))

```



```{r}
table((results$Model[results$TestMSE<4]))

```




```{r readprepare, include=FALSE, eval=F}
# Load the Dataset 
#Stock_Det = read_csv("dow_jones_index.data")
#Stock_Det = DOWdata
#str(Stock_Det)
#glimpse(Stock_Det)

# Convert the price into Numberic value
#Stock_Det$open=as.numeric(gsub("\\$","",Stock_Det$open))
#Stock_Det$high=as.numeric(gsub("\\$","",Stock_Det$high))
#Stock_Det$low=as.numeric(gsub("\\$","",Stock_Det$low))
#Stock_Det$close=as.numeric(gsub("\\$","",Stock_Det$close))
#Stock_Det$next_weeks_open=as.numeric(gsub("\\$","",Stock_Det$next_weeks_open))
#Stock_Det$next_weeks_close=as.numeric(gsub("\\$","",Stock_Det$next_weeks_close))

## Convert the date into Date Format
#Stock_Det$date=mdy(Stock_Det$date)
#summary(Stock_Det)

# Check the missing Values and the missing Column
#sum(is.na(Stock_Det))
#names(which(sapply(Stock_Det, anyNA)))
#Stock_symbol=unique(Stock_Det[c("stock")])
#stoc_det_num=subset(Stock_Det,select = -c(stock))

# There Are totally 60 missing values in the data set . The columns which has the missing values are "percent_change_volume_over_last_wk" "previous_weeks_volume" .Each Column has 30 Missing values based on the number of unique stocks. The missing values are due to the fact that the previous week data (December 2010) is not available. The missing values are getting imputed using the Weighted moving average algorithm, which adds more weight to the previous data for imputation 
#imputed_data=na_ma(Stock_Det)

## Normalize the data set
# The Data Available in the dataset are not not in the same scale. In-order to have an effective analysis We are normalizing the data to be in the same scale.
#params=preProcess(imputed_data,method=c("scale","center","nzv"))
#Scale_stock_det= predict(params,Stock_Det)

# Split the data into Train and test
# Training dataset will contain the stock records for the month January to March. Whereas the testing dataset contains the stock records for the month April to June.
#train_data = subset(Scale_stock_det,(month(date)>=1 & month(date)<=3))
#test_data= subset(Scale_stock_det,(month(date)>=4 & month(date)<=6))
```


```{r  ExploratoryAnalysis}
# The data set contains 16 variables, out of which we are going to consider the below variables
# quarter,date,stock,volume,percent_change_price,percent_change_volume_over_last_wk,percent_change_next_weeks_price,percent_return_next_dividend. <Need to have some explanation why we are not considering the other variables>

#stock_det_cons=subset(Stock_Det,select=-c(open,high,low,close,previous_weeks_volume,next_weeks_open,next_weeks_close,days_to_next_dividend))

#imputed_stock_det_cons=na_ma(stock_det_cons)
#imputed_stock_det_cons=stock_det_cons

#params=preProcess(imputed_stock_det_cons,method=c("scale","center","nzv"))
#Scale_stock_det_cons= predict(params,imputed_stock_det_cons)

#train_stock_det_cons = subset(Scale_stock_det_cons,(month(date)>=1 & month(date)<=3))
#test_stock_det_cons= subset(Scale_stock_det_cons,(month(date)>=4 & month(date)<=6))
```


```{r  ExploratoryAnalysis}
ggplot(data=DOWdata, aes(x=date, y=percent_change_next_weeks_price,color=stock)) +
  geom_point() +
  xlab("")

```


```{r ExploratoryAnalysis}
ggplot(data=DOWdata, aes(x=date, y=volume,color=stock)) +
  geom_point() +
  xlab("")
 
```


```{r ExploratoryAnalysis}
ggplot(data=DOWdata, aes(x=date, y=percent_change_price,color=stock)) +
  geom_point() +
  xlab("")
```
```{r ExploratoryAnalysis}
ggplot(data=DOWdata, aes(x=date, y=percent_change_volume_over_last_wk,color=stock)) +
  geom_point() +
  xlab("")
```

```{r ExploratoryAnalysis}
ggplot(data=DOWdata, aes(x=date, y=percent_return_next_dividend,color=stock)) +
  geom_point() +
  xlab("")

## Based on the time series plot on various stocks, it can be inferred that the data follows the stationary pattern over the variables volume,percent_change_price,percent_change_volume_over_last_wk,percent_change_next_weeks_price and percent_return_next_dividend
```

```{r}
# Execute the linear regression and Check whether any autocorrealtion exists between the time period
stock_lm_formula <- "percent_change_next_weeks_price ~ date+percent_change_price+percent_change_volume_over_last_wk+days_to_next_dividend+percent_return_next_dividend"
```

```{r}
Residual_df<-data.frame(matrix(ncol = 3, nrow = 0))
for(i in unique(train$stock)){

trainstock<-train[train$stock==i,]
stock_lm=lm(formula = stock_lm_formula,data = trainstock)

stock_lm_res=resid(stock_lm)
date=as.Date(trainstock$date,format ="%m/%d/%Y")
stock_nam=rep(i,times=length(trainstock$stock))
Res_data<- data.frame(matrix(stock_nam),matrix(date),matrix(stock_lm_res))
  
Residual_df <- rbind(Residual_df, Res_data)
}
colnames(Residual_df) <- c("Stock","date","residuals")
str(Residual_df)
Residual_df$date<-as_date(Residual_df$date)
```
```{r}
ggplot(data=Residual_df, aes(x=date, y=residuals,color=Stock)) +
  geom_point() +
  geom_line()+
  xlab("")+
  ylab("Residuals")
```


```{r}
for(i in unique(test$stock)){

trainstock<-train[train$stock==i,]
y=train$percent_change_next_weeks_price
lag.plot(y,set.lags = 1:8,layout = c(2,4),labels=FALSE,main = "Lag plot for Percentage of price change for next week")
}

```

```{r}
for(i in unique(test$stock)){

trainstock<-train[train$stock==i,]
y=train$days_to_next_dividend
lag.plot(y,set.lags = 1:8,layout = c(2,4),labels=FALSE,main = "Lag plot for Number of days to next dividend")
}
```
```{r}
for(i in unique(test$stock)){

trainstock<-train[train$stock==i,]
y=train$percent_change_price
lag.plot(y,set.lags = 1:8,layout = c(2,4),labels=FALSE,main = "Lag plot for Percentage of Price changes")
}
```


```{r}
for(i in unique(test$stock)){

trainstock<-train[train$stock==i,]
y=train$percent_change_volume_over_last_wk
lag.plot(y,set.lags = 1:8,layout = c(2,4),labels=FALSE,
         main = "Percent change in volume of stocks traded compared to the previous week")
}
```
```{r}
for(i in unique(test$stock)){

trainstock<-train[train$stock==i,]
y=train$percent_return_next_dividend
lag.plot(y,set.lags = 1:8,layout = c(2,4),labels=FALSE,main = "Percentage of return in the next dividend")
}
```










### I - Executive Summary


### II - The Problem



## III - Review of Related Literature


## IV - Methodology





### V - Data


### VI - Findings


### Appendix

